version: "3"
services:
  web:
    environment:
      DATABASE_PASSWORD: mysecretpassword
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    cap_add:
      - SYS_ADMIN

  db:
    environment:
      POSTGRES_PASSWORD: mysecretpassword
